apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: kublabb
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: docktoranton/kubernetes_labb:latest
          imagePullPolicy: IfNotPresent