apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: kublabb
spec:
  selector:
    app: helloworld
  ports:
    - name: application
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP